### ISSUE TITLE
[Bug] 数据库查询失败

### ISSUE THREAD

**Issue by PythonSmall-Q** [PythonSmall-Q/XMOJ-Script#14]
### 检查项

- [X] 我已确认了XMOJ增强脚本已为最新版，且最新版未修复这个 Bug 。
- [X] 我已在 [Issues 页面](https://github.com/PythonSmall-Q/XMOJ-Script/issues) 中搜索，确认了这一 Bug 未被提交过。

### 描述

数据库查询失败：TypeError: Cannot read properties of undefined (reading 'prepare')

**Comment by PythonSmall-Q** [comment]
@langningchen 麻烦救一下命

**Comment by PythonSmall-Q** [comment]
/-needs-triage

**Comment by langningchen** [comment]
?

**Comment by langningchen** [comment]
你到底

**Comment by langningchen** [comment]
你等等

**Comment by langningchen** [comment]
我正在改代码
