### ISSUE TITLE
[Bug]数据错乱

### ISSUE THREAD

**Issue by PythonSmall-Q** [PythonSmall-Q/XMOJ-Script#20]
### 检查项

- [X] 我已确认了XMOJ增强脚本已为最新版，且最新版未修复这个 Bug 。
- [X] 我已在 [Issues 页面](https://github.com/PythonSmall-Q/XMOJ-Script/issues) 中搜索，确认了这一 Bug 未被提交过。

### 描述

![image](https://github.com/PythonSmall-Q/XMOJ-Script/assets/106425289/a7d3e90a-2f78-44d5-92fd-ab5db0e049a0)
wc数据全乱了 @

**Comment by PythonSmall-Q** [comment]
emm

**Comment by langningchen** [comment]
这个应该是因为……数据库的问题，`bbs_post` 中的 `PostID` 与 `bbs_reply` 中的 `PostID` 不匹配，前者用的新PostID，后者用的旧的

**Comment by langningchen** [comment]
![image](https://github.com/PythonSmall-Q/XMOJ-Script/assets/81672884/3c6dd3c2-e791-47a1-8e1f-48f16675d86c)
但是我这里怎么没事？

**Comment by langningchen** [comment]
我用的是新的 `api.seanoj.edu.eu.org`

**Comment by PythonSmall-Q** [comment]
重新打了一遍

**Comment by PythonSmall-Q** [comment]
不知道为什么已知说用户检查失败

**Comment by PythonSmall-Q** [comment]
@langningchen 能帮个忙看一下吗？

**Comment by PythonSmall-Q** [comment]
编辑讨论改不了

**Comment by PythonSmall-Q** [comment]
发送也有概率炸

**Comment by PythonSmall-Q** [comment]
嗯现在只能在后台编辑了

**Comment by PythonSmall-Q** [comment]
嗯能发送，但是回复可能炸

**Comment by PythonSmall-Q** [comment]
wc又能恢复了

**Comment by PythonSmall-Q** [comment]
![image](https://github.com/PythonSmall-Q/XMOJ-Script/assets/106425289/62fa147c-97a9-493e-bbf7-ffece2325ad8)

**Comment by PythonSmall-Q** [comment]
数据完全乱掉了

**Comment by langningchen** [comment]
旧的数据，还有你可以尝试重新修复一下

**Comment by langningchen** [comment]
我倒是有修复的思路

**Comment by langningchen** [comment]
需要我帮忙吗？

**Comment by PythonSmall-Q** [comment]
可以

**Comment by langningchen** [comment]
我需要重新导出一下数据

**Comment by langningchen** [comment]
你注意做好数据备份

**Comment by langningchen** [comment]
特别是你写的那几篇华丽文章，如果一重新导入，就都没了 @PythonSmall-Q

**Comment by PythonSmall-Q** [comment]
fixed

**Comment by PythonSmall-Q** [comment]
开始新的评论导入

**Comment by langningchen** [comment]
好的

**Comment by langningchen** [comment]
@PythonSmall-Q 顺序反了

**Comment by langningchen** [comment]
![image](https://github.com/PythonSmall-Q/XMOJ-Script/assets/81672884/7f4a115b-1ba1-456b-acaa-b1392691f6c5)

**Comment by PythonSmall-Q** [comment]
艹时间咋整

**Comment by langningchen** [comment]
还有为什么我的这个都是 53 年前

**Comment by langningchen** [comment]
没事，我来

**Comment by PythonSmall-Q** [comment]
ok谢谢

**Comment by langningchen** [comment]
再重发一遍就好了

**Comment by langningchen** [comment]
![image](https://github.com/PythonSmall-Q/XMOJ-Script/assets/81672884/9c93de02-d200-40ff-90ae-e19e65b92f2a)

**Comment by PythonSmall-Q** [comment]
事已至此，小明的OJ增强脚本已经发布了第一个稳定版本！旧版本已经成功对接，升级到1.0.201后接入新的API接口！这将是此项目的一个新纪元！以后的开发工作就由 @zhuchenrui2 (@boomzero) 和 @shanwenxiao (@PythonSmall-Q) 两位同学开发了，祝他们好运，并且能将这个项目做的越来越好！同时， @chenlangning (@langningchen) 也从此退出开发小明的OJ增强脚本的队伍，只做先前代码的疑难解答工作。

**Comment by PythonSmall-Q** [comment]
你的第二条，顺表告诉我一下时间是多少

**Comment by langningchen** [comment]
OK

**Comment by langningchen** [comment]
什么时间多少？

**Comment by PythonSmall-Q** [comment]
就是现在按照cf的计算一个是多少

**Comment by PythonSmall-Q** [comment]
欸我发一个短消息不就知道了么我是蒟蒻

**Comment by langningchen** [comment]
还是不明白 QAQ

**Comment by PythonSmall-Q** [comment]
![image](https://github.com/PythonSmall-Q/XMOJ-Script/assets/106425289/65d7a8c5-76fe-4106-84f9-6a40b6ed6477)
王炸

**Comment by langningchen** [comment]
嘿，我这里没事

**Comment by PythonSmall-Q** [comment]
……

**Comment by langningchen** [comment]
所以没事了？

**Comment by PythonSmall-Q** [comment]
我还是炸

**Comment by PythonSmall-Q** [comment]
摆

**Comment by langningchen** [comment]
@PythonSmall-Q https://github.com/XMOJ-Script-dev/XMOJ-Script/issues/12
