### ISSUE TITLE
[Bug]一直显示验证码不正确

### ISSUE THREAD

**Issue by PythonSmall-Q** [PythonSmall-Q/XMOJ-Script#21]
### 检查项

- [X] 我已确认了XMOJ增强脚本已为最新版，且最新版未修复这个 Bug 。
- [X] 我已在 [Issues 页面](https://github.com/PythonSmall-Q/XMOJ-Script/issues) 中搜索，确认了这一 Bug 未被提交过。

### 描述

![image](https://github.com/PythonSmall-Q/XMOJ-Script/assets/106425289/f5a4edf6-f8c5-4f5e-b5b1-91cd45bf4ee6)

如图，是不是哪里炸了

**Comment by PythonSmall-Q** [comment]
@langningchen 解决了，发现要换成你的那个turnstile

**Comment by langningchen** [comment]
@PythonSmall-Q 又炸了

**Comment by langningchen** [comment]
我自己修了
