### ISSUE TITLE
[Bug] 样例复制区域显示错误

### ISSUE THREAD

**Issue by PythonSmall-Q** [PythonSmall-Q/XMOJ-Script#23]
### 检查项

- [X] 我已确认了XMOJ增强脚本已为最新版，且最新版未修复这个 Bug 。
- [X] 我已在 [Issues 页面](https://github.com/PythonSmall-Q/XMOJ-Script/issues) 中搜索，确认了这一 Bug 未被提交过。

### 描述

![image](https://github.com/PythonSmall-Q/XMOJ-Script/assets/106425289/520306b7-b1d5-42c0-8b91-5582802f817e)

**Comment by PythonSmall-Q** [comment]
looking at it

**Comment by langningchen** [comment]
你的问题吧

**Comment by langningchen** [comment]
![image](https://github.com/PythonSmall-Q/XMOJ-Script/assets/81672884/9d3091f1-e932-4239-8399-4442c4a97c5b)

**Comment by langningchen** [comment]
与 #20 原因应该一样

**Comment by langningchen** [comment]
检查一下你的用户脚本管理器，是不是装了两个脚本

**Comment by PythonSmall-Q** [comment]
![image](https://github.com/PythonSmall-Q/XMOJ-Script/assets/106425289/34d3a648-3f23-41d0-bfde-bec85a5ee6d7)
没有呀

**Comment by langningchen** [comment]
那奇怪

**Comment by langningchen** [comment]
你是不是应该 Transfer 一下 Issue
