### ISSUE TITLE
[Feature Request] 把Code QL设计为每周运行一次

### ISSUE THREAD

**Issue by PythonSmall-Q** [PythonSmall-Q/XMOJ-Script#32]
### 检查项

- [X] 我已确认了XMOJ增强脚本已为最新版，且最新版未实现这一功能。
- [X] 我已在 [Issues 页面](https://github.com/PythonSmall-Q/XMOJ-Script/issues) 中搜索，确认了这一提案未被提交过。

### 描述

今天凌晨看了一眼，免费的时间只有2000分钟一个月CodeQL一次就三四分钟，我们还是省一下吧qwq

**Comment by PythonSmall-Q** [comment]
@boomzero 你看看要不要改一下（？？

**Comment by boomzero** [comment]
@PythonSmall-Q 200分钟是private repo

**Comment by boomzero** [comment]
> @PythonSmall-Q 2000分钟是private repo

Public repo是unlimited

**Comment by boomzero** [comment]
?
